### ISSUE TITLE
IE 8 Support

### ISSUE THREAD

**Issue by nrkarthick** [JoanClaret/jcSlider#3]
This is not working in IE 8 ...  Will u guide ?

**Comment by elboletaire** [comment]
What about upgrading the browser? IE8 is more than 5 years old

**Comment by JoanClaret** [comment]
I'm sorry, but i give support only for IE10+

http://www.w3schools.com/browsers/browsers_explorer.asp

**Comment by elboletaire** [comment]
Although doesn't matter what support gives you @JoanClaret when IE8 does not support CSS3 animations :sweat_smile:
